### ISSUE TITLE
[Bug?] Turning off auto-trim should still trim on save

### ISSUE THREAD

**Issue by ZibingZhang** [zlovatt/obsidian-trim-whitespace#12]
For reasons outlined in https://github.com/zlovatt/obsidian-trim-whitespace/issues/5, it's annoying to have auto-trim turned on. However, I still want to trim my document on save, i.e. when I press `ctrl-s`.

When auto-trim is turned on, manually saving also trims whitespace from the document. However, when auto-trim is turned of, manually saving does _not_ trim whitespace from the document. I'm not sure if this is intended, but my interpretation of auto-trim was that it would do it automatically when editing the document, whereas manually saving should always trim.

My workaround is just to turn on auto-trim, but set the number of seconds to an absurdly high amount.

**Comment by zlovatt** [comment]
Great point! Will implement this for next build.
