### ISSUE TITLE
`$` inside backticks (`) is trimmed?

### ISSUE THREAD

**Issue by calofmijuck** [zlovatt/obsidian-trim-whitespace#17]
In Obsidian, I was typing the following text,

```text
`$$ ... $$`
```

Then, by auto trimming, it became

```text
`$ ... $`
```

Then, again by auto trimming, it became

```text
`$ ... `
```

Is it just me, or is this reproducible on other devices? Thanks.

**Comment by zlovatt** [comment]
Will investigate, thanks!

**Comment by vallentin** [comment]
I just encountered this as well. For me it consistently happens, if `$` is the last character inside the inline code, e.g. `` `$` `` and `` `foo$` `` causes the bug. While `` `$bar` `` and `` `foo$bar` `` does not.

**Comment by zlovatt** [comment]
@vallentin This has been fixed for the next update!

**Comment by calofmijuck** [comment]
Thank you for your time!

**Comment by vallentin** [comment]
Wonderful! Thanks for the plugin. Have a nice weekend 😄
