### ISSUE TITLE
Auto-trim should ignore whitespace adjacent to cursor

### ISSUE THREAD

**Issue by zlovatt** [zlovatt/obsidian-trim-whitespace#5]
If you're idling at the end of a line, thinking about what you want to type next, it's annoying when the plugin trims that intentional trailing space.

Same deal if you've hit newline a few times and are about to type-- having it remove those is irksome. 

Suggested solve: ignore anything contiguous with the cursor.

**Comment by zlovatt** [comment]
Note to self:
- Have found (and stashed) a solution by splitting the input text based on the cursor, snapping to prior/next word boundary
- Problem is the 'word boundary' detector fails on code fences / inline code
  - can be adapted to detect this, however there's no clean way to detect whether the cursor is currently _inside_ a code block
- The solution also behaves strangely when there's a selection region set, as it'll ignore anything touching within the range (vs just ignoring the cursor-contiguous whitespace blocks)

On hold for now / indefinitely 😔

**Comment by orlade** [comment]
At a minimum, can you just ignore the current (cursor) line when auto-trimming?

**Comment by velebit** [comment]
I made PR #13 as an attempt to solve this.

**Comment by zlovatt** [comment]
@universemaster Completed in v0.3.0
