### ISSUE TITLE
Remove whitespace replaces inline code with code block

### ISSUE THREAD

**Issue by andrezgz** [zlovatt/obsidian-trim-whitespace#7]
This plugin is great, but in one of my code notes it had messed up several parts. I have oversimplified the case to the bare minimum and share this reproducible version.

````
A line with several inline codes

`1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`

Two code blocks

```js
console.log(1)
```

```js
console.log(2)
```
````

When I execute the command "Remove whitespace in document", I get this:

````
A line with several inline codes

`1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, ```js
console.log(2)
```0, `10`

Two code blocks

```js
console.log(1)
```

TRIM_WHITESPACE_REPLACE_1
````

The inline code `` `9` `` gets replaced with the second code block, and instead of the second code block now there is a placeholder `TRIM_WHITESPACE_REPLACE_1`

The content of inline codes and code blocks do not change the result. It seems that the quantity and the position are what matters here. Adding more instances of inline code and code blocks, more of them get affected.

The "Skip code blocks" option is **enabled**, in order to avoid changing indentation whitespace inside them.

**Comment by zlovatt** [comment]
Noted, thanks for the ticket!

This wasn't caught in my test cases; will explore.

**Comment by zlovatt** [comment]
@andrezgz this should be fixed! Sorry about that.

**Comment by andrezgz** [comment]
Thanks @zlovatt! It seems to be working right now
