### ISSUE TITLE
Only the first code block is skipped

### ISSUE THREAD

**Issue by andrezgz** [zlovatt/obsidian-trim-whitespace#8]
I have each of the trimming rules enabled (for trailing, leading and multiple characters) and "Skip code blocks" option too. When I choose to "Remove whitespace in document", the first code block is skipped, but all of the subsequent ones get targeted by the rules and its whitespace is removed or turned into one (for a group of multiple inline spaces).

The following is the minimum reproducible test case I could build:

````
Identical code blocks

```js
function log(text) {
    console.log   (`->  ${text}  <-`);  
    // the previous line has 2 trailing spaces
}
```

```js
function log(text) {
    console.log   (`->  ${text}  <-`);  
    // the previous line has 2 trailing spaces
}
```
````

When I execute the command "Remove whitespace in document", I get this:

````
Identical code blocks

```js
function log(text) {
    console.log   (`->  ${text}  <-`);  
    // the previous line has 2 trailing spaces
}
```

```js
function log(text) {
console.log (`->  ${text}  <-`);
// the previous line has 2 trailing spaces
}
```
````

For the  `console.log` for the second code block note that leading and trailing whitespace was removed, and the 3 inline spaces were converted into a single one.

The second code block should have been skipped as the first one.

**Comment by zlovatt** [comment]
Ack, good find. Was a weird one to track down– it's not about the first vs others, it's about the blocks being "too close together."

Going to hold off on another patch just in case something else comes up right after I release it 😅
